In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("play_tennis.csv")
data.head()
data.drop(columns= ['day'], inplace=True)

In [3]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [4]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [5]:
py = 9/14
pn = 5/14

In [8]:
pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [9]:
pon= 0
prn = 2/5
psn = 3/5

poy= 4/9
pry = 3/9
psy = 2/9

In [10]:
pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [11]:
Pcooln= 1/5
photn = 2/5
pmildn = 2/5

pcooly = 3/9
photy = 2/9
pmildy = 4/9

In [12]:
pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [13]:
phighn = 4/5
pnormaln = 1/5

phighy = 3/9
pnormaly = 6/9

In [14]:
pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [15]:
pstrongn = 3/5
pweakn = 2/5

pstrongy=  3/9
pweaky = 6/9

In [16]:
# Outlook = Sunny, temp = hot, humidity = high , wind=weak 
Pyes = py*psy*photy*phighy*pweaky
print(Pyes)

0.007054673721340388

In [17]:
Pno = pn*psn*photn*phighn*pweakn
print(Pno)

0.02742857142857143

In [18]:
# no playing tennis